### ISSUE TITLE
Cmder dont run APP

### ISSUE THREAD

**Issue by Mxater** [GrzegorzKozub/VisualStudioExtensions#4]
I try to run my app from Visual storio to Cmder/ComEmu, but still run in separate CMD windows.

When I click in ComEmu, only open the Cmder in default folder.
![image](https://user-images.githubusercontent.com/4630666/30345097-445910c4-97da-11e7-8c24-a88f6ce362d0.png)

If I click in Run, open in separate Windows.
![image](https://user-images.githubusercontent.com/4630666/30345156-79a300aa-97da-11e7-8a78-0d3ea8ca253f.png)

**Comment by GrzegorzKozub** [comment]
Hi there and thanks for using my extension.

Unfortunately the experience you are looking for is not provided by Visual Studio to my knowledge. Using the "play button" or hitting `F5` will, depending on the app, launch its own process (along with a fresh cmd instance if that's a console app) or a web server like IIS or IIS Express.

Currently, as far as I tested, this is also not supported in a very promising extension called [Whack Whack Terminal](https://marketplace.visualstudio.com/items?itemName=DanielGriffen.WhackWhackTerminal) but let's hope Daniel finds a way to make it.

Extensions like ConEmu Launcher are much simpler that you expect ;) All they do is open a terminal that is completely disconnected from Visual Studio and let you do things like Git or NPM command line. If your app runs on .NET Core, then you can type `dotnet run` in such terminal to achieve what you're looking for.

If you just want to see some messages from your app in any Visual Studio tool window, use Output window and `System.Diagnostics.Debug.WriteLine()` method from your code.

Good news is that runnis integrated and supported very well in Visual Studio Code that aims at developers with a more terminal-focused workflow.

Hope that helps!
