### ISSUE TITLE
Visual Studio 2019 support

### ISSUE THREAD

**Issue by RomanDidenko** [GrzegorzKozub/VisualStudioExtensions#5]
Would be great to have Visual Studio 2019 support, please.

**Comment by zvarg** [comment]
I have added a commit for supporting VS 2019. Waiting for accepting pull request. Alternatively you can use my fork found [here](https://github.com/zvarg/VisualStudioExtensions) until it's accepted, but I recommend using Grzegorz's extensions.

**Comment by zvarg** [comment]
My pull request has been approved. Lets forget deprecated APIs warning in VS for a moment. That's another story.
